/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaQuestGenerics;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        FruitsList<Apple> appleList = new FruitsList<>();
        FruitsList<Banana> bananaList = new FruitsList<>();
        FruitsList<Pear> pearList = new FruitsList<>();
        
        Apple apple1 = new Apple();
        Banana banana1 = new Banana();
        Banana banana2 = new Banana();
        Pear pear1 = new Pear();
        Pear pear2 = new Pear();
        Pear pear3 = new Pear();
        
        appleList.add(apple1);
        bananaList.add(banana1);
        bananaList.add(banana2);
        pearList.add(pear1);
        pearList.add(pear2);
        pearList.add(pear3);

        for (int i = 0; i < appleList.size(); i++) {
            System.out.println("TEST-Apple: " + appleList.get(i));
        }

        for (int i = 0; i < bananaList.size(); i++) {
            System.out.println("TEST-Banana: " + bananaList.get(i));
        }

        for (int i = 0; i < pearList.size(); i++) {
            System.out.println("TEST-Pear: " + pearList.get(i));
        }

        System.out.println("TEST-ClassName-Apple: " + appleList.getClass().getName());
        System.out.println("TEST-ClassName-Banana: " + bananaList.getClass().getName());
        System.out.println("TEST-ClassName-Pear: " + pearList.getClass().getName());
        
    }

}
