/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaQuestGenerics;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    private final FruitsList<Apple> appleList = new FruitsList<>();
    private final FruitsList<Banana> bananaList = new FruitsList<>();
    private final FruitsList<Pear> pearList = new FruitsList<>();

    @Test
    public void hasCorrectAppleClass() {
        assertEquals("JavaQuestGenerics.FruitsList", appleList.getClass().getName());
    }

    @Test
    public void hasCorrectBananaClass() {
        assertEquals("JavaQuestGenerics.FruitsList", bananaList.getClass().getName());
    }

    @Test
    public void hasCorrectPearClass() {
        assertEquals("JavaQuestGenerics.FruitsList", pearList.getClass().getName());
    }

}
